### ISSUE TITLE
Tiny buglet at line 331 in piclone.c?

### ISSUE THREAD

**Issue by GussyFinkNottle** [raspberrypi/piclone#20]
I'm almost sure (it's been a while...) that you meant not "if (uuid[4] = '-')" but "if (uuid[4] == '-')".

**Comment by spl237** [comment]
Yes, you're quite right - well spotted! It's only in a belt-and-braces check, so that test is unlikely to ever have any effect, but that's no excuse for it being wrong... I'll fix it - many thanks.
