### ISSUE TITLE
Piclone on amd64 Ubuntu

### ISSUE THREAD

**Issue by saket424** [raspberrypi/piclone#30]
I am attempting to use piclone using the amd64 Deb package https://archive.raspberrypi.org/debian/pool/main/p/piclone/piclone_0.16_amd64.deb and I assume the boot grub/efi partition is msdos and hence piclone terminates

Any known work arounds or suggestions to backup a live Ubuntu amd64 system ? Btw Ubuntu arm64 system does work as it does not have the msdos partition

if (strncmp (buffer, "Partition Table: msdos", 22))
    {
        terminate_dialog (_("Non-MSDOS partition table on source."));
        return NULL;
    }

**Comment by spl237** [comment]
Sorry, can't help - piclone was designed to work on Raspbian; I have no knowledge of how Ubuntu might differ in a fashion which may affect it.
