### ISSUE TITLE
start piclone as root, cannot see drives

### ISSUE THREAD

**Issue by MrEnergy64** [raspberrypi/piclone#36]
Hello,

I compiled you piclone successfully on raspi ubuntu 20.04.2 tls. When I start the piclone as root I cannot see/choice an drive in the menu.

When I start it as normal user, I can see and choice the drives, after start I see the window with the delete drive messages and then I just see Checking source.... and in the terminal I see:

ubuntu@ubuntu:~/Downloads/piclone-master$ piclone
WARNING: You are not superuser.  Watch out for permissions.
Error: Error opening /dev/mmcblk0: Permission denied

Linux ubuntu 5.4.0-1028-raspi #31-Ubuntu SMP PREEMPT Wed Jan 20 11:30:45 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

What do I wrong?

**Comment by spl237** [comment]
piclone needs to access the session D-Bus to see drives, which it cannot do if started as sudo. You need to use the command line in the piclone.desktop file to start with the appropriate permissions.
