### ISSUE TITLE
configure.ac

### ISSUE THREAD

**Issue by mydogteddy** [raspberrypi/piclone#41]
Using ubuntu 22.04 I had to remove line 2 from configure.ac AC_CONFIG_MACRO_DIR([m4])
To make it compile.

**Comment by spl237** [comment]
That line is required for it to compile under Raspberry Pi OS, which is the intended target OS, so I'm afraid that's not something we're going to change.

**Comment by mydogteddy** [comment]
OK, thanks for the response, I am using Ubuntu 22.04 on my RPi 4 which seems infinitely better than the Raspberry Pi OS, plus by removing line 2 it also means I can compile the same and use SD Card Copier on my laptop which also has Ubuntu 22.04 on it.
However, I do understand your comment
