### ISSUE TITLE
Can I create an executable file to run PiClone and do regular backups of my SD card?

### ISSUE THREAD

**Issue by elporsche** [raspberrypi/piclone#45]
Hi,

I'm wondering if it's possible to create an executable file that runs e.g, every week or so, where I can pass on the user-required input to PiClone: root password, the device to be copied from, the device to copy to, and to tick the New Partition UUIDs box. I would then have the executable file run every week or so.

Thanks in advance!

**Comment by spl237** [comment]
No, not really from a GUI application like this. Your best bet is probably to set up what is known as a cron job, which is how you trigger code to run at specific times - https://en.wikipedia.org/wiki/Cron 

From that you could trigger a call to the "backup" script you will find in the src subdirectory of this repository, which is an old command-line version of piclone. Be warned that said backup script has not been maintained for a while, so might not do everything that is required and could need tweaking.
