### ISSUE TITLE
Question: What license is piclone licensed under?

### ISSUE THREAD

**Issue by libewa** [raspberrypi/piclone#46]
The piclone repo currently has no `LICENSE` file, which would imply that it is unfree. Could you please clarify this by adding a `LICENSE` or `COPYING` file to the repo?

**Comment by libewa** [comment]
ok, I just found the copyright file in /debian/copyright, but could you please create a license file anyway?

**Comment by spl237** [comment]
Copyright file in debian subdirectory is all that is required.
