### ISSUE TITLE
Able to compile/build/make piclone on Armbian 23.10.1/Ubuntu 22.04, but no reference to how to create desktop icon, say in Gnome?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [raspberrypi/piclone#47]
Able to compile/build/make piclone on Armbian 23.10.1/Ubuntu 22.04, had to add the following:

# apt install intltool libgtk-3-dev

But no reference to how to create desktop icon, say in Gnome?  Application found via search so was easy to add to the Gnome dash panel.

Unfortunately, fails with unable to read source error?  Well would have been nice if it worked.  Any chance a way to get around the error?

```
# cat /etc/os-release
PRETTY_NAME="Armbian 23.11.1 jammy"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.armbian.com"
SUPPORT_URL="https://forum.armbian.com"
BUG_REPORT_URL="https://www.armbian.com/bugs"
PRIVACY_POLICY_URL="https://www.armbian.com"
UBUNTU_CODENAME=jammy
ARMBIAN_PRETTY_NAME="Armbian 23.11.1 jammy"

# uname -a
Linux schizo.dachshund-digital.org 5.10.110-rockchip-rk3588-indiedroid #1 SMP PREEMPT Thu Mar 9 02:22:35 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by spl237** [comment]
The icon lives in the package pixflat-icons, so sudo apt install pixflat-icons. But I'm afraid I don't know how to use it in a desktop shortcut on Ubuntu - you'll need to ask someone who knows about Ubuntu for that.

**Comment by Jibun-no-Kage** [comment]
Yeah... the icon was one thing.  But the real issue is the application fails once it tries to parse out what is on the source media selected.  Which is odd, given the basic layout of the media is comparable to Pi OS images.  So the fact that the tools fails, means there is something 'Pi' specific in play.  To bad, the tool is quite nice, would be really cool if it was more cross-platform, at least in the same distribution family of debian/ubuntu for example.
