### ISSUE TITLE
Cannot create file system

### ISSUE THREAD

**Issue by Cisecodev** [raspberrypi/piclone#6]
Raspberry Pi 2 - fresh rasbian install 2016-05-27 (not Noobs).
8GB SD card running Raspbian, another 8GB card (unformatted) in /dev/sda
Run SD Card Copier from menu
Result fat partition gets created and the I get the error "Could not create file system.".
Ext4 partition is not created.
Repeatable.

Rpi-clone works fine.

**Comment by spl237** [comment]
Check the destination card is not write-protected. Try formatting the destination card in another machine and try again. The error message is produced by mkfs being unable to perform an operation on the card; there is probably a problem with your card or card writer. 

To help diagnose this, please post the output of 
"sudo lsblk -o name,uuid"

**Comment by Cisecodev** [comment]
> Check the destination card is not write-protected

It is not write protected - I have tried several

> Try formatting the destination card in another machine and try again.

Done - no difference

> there is probably a problem with your card or card writer

tried three different makes not has an issue before.

As I said Rpi-clone works

Running Piclone from a terminal
![image](https://cloud.githubusercontent.com/assets/1893099/15777311/1b113fb6-2986-11e6-9844-f9fa277088d7.png)

Output of lsblk -o name,uuid
NAME        UUID
sda
└─sda1      9016-4EF8
mmcblk0
├─mmcblk0p1 2D2D-CD16
└─mmcblk0p2 2f840c69-cecb-4b10-87e4-01b9d28c231c

**Comment by spl237** [comment]
OK, for some reason, /dev/sda1 on the target is not being unmounted when piclone asks it to; or actually looks as if it is being unmounted and then something else is remounting it before mkfs has time to do anything. Are you running any other software or processes that might be trying to access the card reader at the same time?

If you manually do a sudo umount /dev/sda1 before you start, does that help?

**Comment by Cisecodev** [comment]
> Are you running any other software or processes that might be trying to access the card reader at the same time?

nothing else running - let alone anything that might access the SD card

> If you manually do a sudo umount /dev/sda1 before you start, does that help?

No difference, same error message

df before run
/dev/root        7508524 3522752   3626132  50% /
devtmpfs          469544       0    469544   0% /dev
tmpfs             473876       0    473876   0% /dev/shm
tmpfs             473876    6408    467468   2% /run
tmpfs               5120       4      5116   1% /run/lock
tmpfs             473876       0    473876   0% /sys/fs/cgroup
/dev/mmcblk0p1     64456   20992     43464  33% /boot
tmpfs              94776       4     94772   1% /run/user/1000

then run piclone - get the error - it is mounted
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root        7508524 3522752   3626132  50% /
devtmpfs          469544       0    469544   0% /dev
tmpfs             473876       0    473876   0% /dev/shm
tmpfs             473876    6408    467468   2% /run
tmpfs               5120       4      5116   1% /run/lock
tmpfs             473876       0    473876   0% /sys/fs/cgroup
/dev/mmcblk0p1     64456   20992     43464  33% /boot
tmpfs              94776       4     94772   1% /run/user/1000
/dev/sda1       31248384 5292544  25955840  17% /media/usb0

**Comment by spl237** [comment]
It looks like something peculiar to your setup; I've tested piclone a lot and not seen a failure like this before. Does it happen with a completely clean install of Raspbian? What else have you installed?

Check the table of mounted devices - cat /proc/mounts, I think. Then force /dev/sda1 to unmount - sudo umount /dev/sda1 - and check the table again. Then run piclone - if it fails, check the table a third time - what is mounted in all three cases?

**Comment by Cisecodev** [comment]
Tried brand new fresh install of Rasbian, installed xrdp - (I run headless) and ran Pi clone - it worked fine.

I just need to work out what I might have installed (I thought nothing) - or maybe a corrupt installation.

Closing this
